name: Build

on:
  workflow_dispatch:
    inputs:
      configuration:
        description: Target build configuration
        required: true
        type: choice
        default: Develop
        options:
          - Debug
          - Develop
          - Profile
          - Release

jobs:
  build:
    name: Build Target
    uses: ./.github/workflows/build-dispatch.yaml
    strategy:
      matrix:
        project: [all]
        pipeline: [x64]
        include:
          - host: windows-latest
    with:
      host-platform: ${{ matrix.host }}
      target-platform: 'win32'
      targets: "${{ matrix.project }}-${{ matrix.pipeline }}-${{ inputs.configuration }}"
