name: Code Validation
run-name: Code Validation (${{ github.ref_name }})

on:
  push:
    paths:
      - 'source/**'
      - '.github/workflows/build-dispatch.yaml'
      - '.github/workflows/build-validate-code.yaml'
      - '!source/data/**'
  workflow_dispatch:

jobs:
  validate:
    name: Validate (${{ matrix.project }}-${{ matrix.pipeline }}-${{ matrix.config }}, ${{ matrix.host }})
    uses: ./.github/workflows/build-dispatch.yaml
    strategy:
      matrix:
        host: [windows-latest, ubuntu-latest]
        project: [all]
        pipeline: [x64]
        config: [Debug,Develop,Profile,Release]
        include:
          - host: ubuntu-latest
            target-platform: linux
            clang-version: '20'
          - host: 'windows-latest'
            target-platform: win32
    with:
      host-platform: ${{ matrix.host }}
      target-platform: ${{ matrix.target-platform }}
      targets: "${{ matrix.project }}-${{ matrix.pipeline }}-${{ matrix.config }}"
      clang-version: ${{ matrix.clang-version || '' }}
