name: Build

on:
  workflow_dispatch:
    inputs:
      configuration:
        description: Target build configuration
        required: true
        type: choice
        default: Develop
        options:
          - Debug
          - Develop
          - Profile
          - Release

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Log information
        run: |
          echo Initializing for ${{ inputs.configuration }}
      - name: Initialize the workspace
        uses: ./.github/actions/ibt-workspace-init@hotfix-may-13
