name: Code Validation
run-name: Code Validation (${{ github.ref_name }})

on:
  push:
    paths:
      - 'source/**'
      - '!source/data/**'

jobs:
  validate:
    name: Validate (${{ matrix.project }}-${{ matrix.pipeline }}-${{ matrix.config }}, ${{ matrix.host }})
    uses: ./.github/workflows/build-dispatch.yaml
    strategy:
      matrix:
        project: [all]
        config: [Debug,Develop,Profile,Release]
        include:
          - host: windows-latest
            pipeline: 'x64'
          - host: ubuntu-latest
            pipeline: 'x64-Clang'
            clang-version: 20
    with:
      host-platform: ${{ matrix.host }}
      target: "${{ matrix.project }}-${{ matrix.pipeline }}-${{ matrix.config }}"
      clang-version: ${{ matrix.clang-version || 0 }}
