name: Style check

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    name: Run check
    runs-on: ubuntu-latest
    container: tomeinc/uncrustify:0.73.0
    steps:
      - uses: actions/checkout@v2
      - name: Style check (Uncrustify)
        run: |
          git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }}..${{ github.sha }}
          uncrustify -v
