name: Style check

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Style check (Uncrustify)
        uses: dolik-rce/actions-uncrustify@v1.1
        with:
          configPath: source/code_style.cfg
          fileMask: '*.cxx *.hxx'
